#!/usr/bin/env python3
"""crackme_1_by_huskyhusky keygen.

The binary is a 1KB hand written VM. Its bytecode walks the password and keeps
a running total

    A = -75238 + sum(w[i] * password[i])

and the verdict at VM pc 4 is `jump to the Wrong branch if A != 0`, so any
input whose weighted sum hits 75238 is accepted.

w[] is generated by the bytecode, not stored: it is the odd numbers run
through a primality test that leaks (9, 15, 25, 49 and 121 all pass), which is
why the table below is *almost* the primes.

no args prints a key, or pass a length.
"""
import sys

TARGET = 75238
LO, HI = 0x21, 0x7E                    # graphic ASCII, no whitespace

MULTIPLIERS = [
    3, 5, 7, 9, 11, 13, 15, 17, 19, 23, 25, 29, 31, 37, 41, 43, 47, 49, 53,
    59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 121, 127,
    131, 137, 139, 149, 151,
]


def total(key: bytes) -> int:
    return sum(w * c for w, c in zip(MULTIPLIERS, key))


def check(key: bytes) -> bool:
    return len(key) <= len(MULTIPLIERS) and total(key) == TARGET


def keygen(length=32):
    """Any printable string of this length whose weighted sum is TARGET."""
    w = MULTIPLIERS[:length]
    if not sum(w) * LO <= TARGET <= sum(w) * HI:
        return None
    c = [LO] * length
    cur = sum(x * LO for x in w)

    # fill the heavy positions first, but leave a remainder the 3 and 5 slots
    # can finish off exactly (3a + 5b covers everything from 8 upwards)
    SLACK = 400
    for i in sorted(range(2, length), key=lambda j: -w[j]):
        room = min(HI - LO, max(0, (TARGET - SLACK - cur) // w[i]))
        c[i] += room
        cur += room * w[i]

    rest = TARGET - cur
    for b in range(HI - LO + 1):
        a, r = divmod(rest - 5 * b, 3)
        if r == 0 and 0 <= a <= HI - LO:
            c[0] += a
            c[1] += b
            break
    else:
        return None
    key = bytes(c)
    return key if check(key) else None


def main():
    lengths = [int(a) for a in sys.argv[1:]] or [24, 28, 32]
    for n in lengths:
        k = keygen(n)
        if k is None:
            print(f'len {n:2}: unreachable')
        else:
            print(f'len {n:2}: {k.decode()}   sum={total(k)}')


if __name__ == '__main__':
    main()
